---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  nodes_path: test/fixtures/nodes
  clients_path: test/fixtures/clients
  environments_path: test/fixtures/environments
  data_bags_path: test/fixtures/data_bags
  client_rb:
    environment: test

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[test]
      - recipe[vault-template::default]
    attributes:
