---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  nodes_path: test/fixtures/nodes
  clients_path: test/fixtures/clients
  data_bags_path: test/fixtures/data_bags

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[test::chef_vault_secret]
      - recipe[vault-template::default]
    attributes:
      chef-vault:
        databag_vault: false
